github: enable Windows 2019 for integration test
Integration test fails on Windows 2019 with following errors:

cargo xtest --target /d/a/td-shim/td-shim/devtools/rustc-targets/x86_64-custom.json -p test-td-exception
WARNING: There is no root package to read the cargo-xbuild config from.
error: target path "/d/a/td-shim/td-shim/devtools/rustc-targets/x86_64-custom.json" is not a valid file
Error: target path "/d/a/td-shim/td-shim/devtools/rustc-targets/x86_64-custom.json" is not a valid file
Caused by:
  The system cannot find the path specified. (os error 3)
mingw32-make: *** [Makefile:97: integration-test-test-td-exception] Error 101
Error: Process completed with exit code 1.

Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>