Fix version of crate x86_64.
Latest version "0.14.7" of x86_64 fails to build due to error[E0658]:
panicking in constant functions is unstable.

Signed-off-by: Jiaqi Gao <jiaqi.gao@intel.com>